server:
  undertow:
    worker-threads: 16
    direct-buffers: true
    buffer-size: 1024
spring:
  datasource:
    url: jdbc:mariadb://localhost/wparts
    username: wparts
    password: wparts@1243
  jpa:
    properties:
       hibernate:
         dialect: org.hibernate.dialect.MariaDBDialect
         connection:
           useUnicode: true
           characterEncoding: utf-8
           CharSet: utf-8
  data:
    rest:
      base-path: api
---
spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
---
spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: validate
